// AUTO-GENERATED by scripts/generate-reserved-slugs.mjs.
// Do not edit by hand — edit backend/zserver/src/modules/workspace/reserved_slugs.json
// and run `pnpm generate:reserved-slugs`.

/**
 * Slugs reserved because they collide with frontend top-level routes,
 * platform features, or web standards.
 *
 * Single source of truth: `backend/zserver/src/modules/workspace/reserved_slugs.json`.
 * The Zig backend embeds that JSON; this file is regenerated from it.
 *
 * Convention for new global routes (CLAUDE.md): use a single word
 * (`/login`, `/inbox`) or `/{noun}/{verb}` (`/workspaces/new`). Hyphenated
 * root-level word groups (`/new-workspace`, `/create-team`) collide with
 * common user workspace names — see PR for full discussion.
 */
export const RESERVED_SLUGS: ReadonlySet<string> = new Set([
  // `onboarding` is historical, kept reserved post-removal of the route.
  "login",
  "logout",
  "signin",
  "signout",
  "signup",
  "auth",
  "oauth",
  "callback",
  "invite",
  "invitations",
  "verify",
  "reset",
  "password",
  "onboarding",

  // `/homepage` landing variant in apps/web.
  "api",
  "admin",
  "multica",
  "www",
  "new",
  "home",
  "homepage",
  "dashboard",
  "help",
  "about",
  "pricing",
  "changelog",
  "docs",
  "support",
  "status",
  "legal",
  "privacy",
  "terms",
  "security",
  "contact",
  "contact-sales",
  "blog",
  "careers",
  "press",
  "download",
  "usecases",

  // Account / billing (likely-future global routes in the avatar menu)
  "profile",
  "account",
  "billing",
  "notifications",
  "search",
  "members",

  // page; `teams` is reserved for future team management.
  "issues",
  "projects",
  "autopilots",
  "agents",
  "squads",
  "inbox",
  "my-issues",
  "usage",
  "runtimes",
  "skills",
  "settings",
  "workspaces",
  "teams",

  // slugs that read like API identifiers.
  "v1",
  "v2",
  "graphql",
  "webhooks",
  "sdk",
  "tokens",
  "cli",

  // these paths are ever proxied through the web origin.
  "health",
  "readyz",
  "healthz",
  "ws",
  "metrics",
  "ping",

  // messaging.
  "postmaster",
  "abuse",
  "noreply",
  "webmaster",
  "hostmaster",

  // subdomain-takeover attempts.
  "mail",
  "ftp",
  "static",
  "cdn",
  "assets",
  "public",
  "files",
  "uploads",
]);

export function isReservedSlug(slug: string): boolean {
  return RESERVED_SLUGS.has(slug);
}
