import { defineConfig } from "vite";
import { solidStart } from "@solidjs/start/config";
import { nitro } from "nitro/vite";
import tailwindcss from "@tailwindcss/vite";
import { solidMdx } from "./scripts/vite-plugin-solid-mdx.mjs";
import { readFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const routesJson = join(here, ".source", "routes.json");
// Prerender routes are generated by scripts/build-source.mjs (run before
// `vite build`). In dev they are irrelevant — Nitro prerender only runs
// during build.
const prerenderRoutes = existsSync(routesJson)
  ? JSON.parse(readFileSync(routesJson, "utf8"))
  : [];

export default defineConfig({
  server: {
    // Keep the old Next dev port (docs runs separately from apps/web:3000)
    port: 4000,
  },
  // The site is served under /docs (basePath parity with the old Next app).
  // This prefixes asset URLs (/_build/...) so they resolve behind the
  // reverse proxy that maps /docs -> .output/public.
  base: "/docs/",
  nitro: {
    // Nitro v3 beta: prerender is driven by routeRules with prerender: true.
    // Every docs route generated by scripts/build-source.mjs becomes a static
    // HTML page in .output/public.
    routeRules: Object.fromEntries(prerenderRoutes.map((r: string) => [r, { prerender: true }])),
    prerender: { failOnError: true },
  },
  plugins: [
    solidMdx(),
    solidStart({ ssr: true }),
    nitro(),
    tailwindcss(),
  ],
  resolve: {
    alias: {
      // MDX files import their components via `@/` (repo convention) and
      // `fumadocs-ui/...` (legacy Fumadocs path). Both resolve to our
      // Solid implementations so content files stay untouched.
      "@": join(here, "src"),
      // @mdx-js/mdx appends "/jsx-runtime" to jsxImportSource
      "@mdx-runtime/jsx-runtime": join(here, "src", "lib", "mdx-runtime.ts"),
      "fumadocs-ui/components/callout": join(here, "src", "components", "callout.tsx"),
    },
  },
});
